# Generated by Django 2.1.3 on 2018-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_email', models.CharField(max_length=45, unique=True)),
                ('consumer_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.CharField(max_length=45, unique=True)),
                ('seller_password', models.CharField(max_length=45)),
            ],
        ),
    ]
