# Generated by Django 2.1.3 on 2018-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_phone',
            field=models.CharField(max_length=11),
        ),
    ]
